
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 15;
  public static final int STRING_LITERAL = 34;
  public static final int LTE = 21;
  public static final int UMINUS = 16;
  public static final int LPAREN = 29;
  public static final int SEMI = 27;
  public static final int INT = 2;
  public static final int MINUS = 13;
  public static final int RPAREN = 30;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int LT = 20;
  public static final int OR = 25;
  public static final int COMMA = 28;
  public static final int PLUS = 12;
  public static final int ASSIGN = 17;
  public static final int IF = 6;
  public static final int ID = 33;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 9;
  public static final int TRUE = 10;
  public static final int error = 1;
  public static final int NEQ = 19;
  public static final int VOID = 5;
  public static final int EQ = 18;
  public static final int GTE = 23;
  public static final int TIMES = 14;
  public static final int LBRACE = 31;
  public static final int ELSE = 7;
  public static final int WHILE = 8;
  public static final int FLOAT = 3;
  public static final int RBRACE = 32;
  public static final int FLOAT_LITERAL = 36;
  public static final int FALSE = 11;
  public static final int GT = 22;
  public static final int INT_LITERAL = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "VOID",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "TRUE",
  "FALSE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "UMINUS",
  "ASSIGN",
  "EQ",
  "NEQ",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "AND",
  "OR",
  "NOT",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "ID",
  "STRING_LITERAL",
  "INT_LITERAL",
  "FLOAT_LITERAL"
  };
}

